export { default as Header } from './header'
export { default as Bio } from './bio'
export { default as TableOfContents } from './TableOfContents'
export { default as Content } from './content'
export { default as Footer } from './Footer'
